"""add user roles

Revision ID: 32c11fcebb4d
Revises: ffea205bf773
Create Date: 2026-09-04 21:55:21.316307

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32c11fcebb4d"
down_revision: Union[str, Sequence[str], None] = "ffea205bf773"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role"),
    )
    # ### end Alembic commands ###

    # Autogenerate does not write this: without it every user who registered
    # before roles existed would come back with no privileges at all.
    op.execute("INSERT INTO user_roles (user_id, role) SELECT id, 'user' FROM users")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    # ### end Alembic commands ###
