import os
from argparse import Namespace
from collections.abc import Iterator
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.exc import SQLAlchemyError

from app.config import config

ALEMBIC_INI = Path(__file__).resolve().parents[3] / "alembic.ini"

# One scratch database per xdist worker, so a parallel run does not have two
# tests creating and dropping the same schema underneath each other.
SCRATCH_DATABASE = f"migrations_test_{os.environ.get('PYTEST_XDIST_WORKER', 'gw')}"

SERVER_URL, _, _ = config.DATABASE_URL.rpartition("/")
SCRATCH_URL = f"{SERVER_URL}/{SCRATCH_DATABASE}"


def _server_is_reachable() -> bool:
    try:
        with create_engine(f"{SERVER_URL}/").connect():
            return True
    except SQLAlchemyError:
        return False


pytestmark = [
    pytest.mark.e2e,
    pytest.mark.skipif(
        not _server_is_reachable(),
        reason=f"no database server at {SERVER_URL}",
    ),
]


def alembic_config(url: str) -> Config:
    """The project's Alembic configuration, pointed at ``url``.

    env.py takes the URL from ``-x url=...`` before falling back to the
    application's own configuration, which is what lets these tests run against
    a scratch database instead of the developer's.
    """
    alembic_cfg = Config(str(ALEMBIC_INI))
    alembic_cfg.cmd_opts = Namespace(x=[f"url={url}"])
    return alembic_cfg


@pytest.fixture
def empty_database() -> Iterator[str]:
    engine = create_engine(f"{SERVER_URL}/", isolation_level="AUTOCOMMIT")
    with engine.connect() as connection:
        connection.execute(text(f"DROP DATABASE IF EXISTS {SCRATCH_DATABASE}"))
        connection.execute(text(f"CREATE DATABASE {SCRATCH_DATABASE}"))
    try:
        yield SCRATCH_URL
    finally:
        with engine.connect() as connection:
            connection.execute(text(f"DROP DATABASE IF EXISTS {SCRATCH_DATABASE}"))


class TestMigrations:
    def test_the_migrations_build_the_schema_the_entities_describe(
        self, empty_database: str
    ):
        """The check Django makes you remember to run.

        Applying every migration to an empty database must leave a schema that
        autogenerate finds nothing to add to. If an entity was changed without
        a migration being written, `alembic check` reports the difference and
        this fails -- at the point the change is made, rather than at the point
        it is deployed.
        """
        alembic_cfg = alembic_config(empty_database)

        command.upgrade(alembic_cfg, "head")

        try:
            command.check(alembic_cfg)
        except AutogenerateDiffsDetected as diffs:
            pytest.fail(
                "The entities and the migrations disagree. Write a migration "
                f"with `alembic revision --autogenerate`:\n{diffs}"
            )

    def test_every_migration_can_be_undone(self, empty_database: str):
        # A migration that cannot be reversed is one a bad deployment cannot be
        # backed out of, so downgrade is exercised rather than assumed.
        alembic_cfg = alembic_config(empty_database)

        command.upgrade(alembic_cfg, "head")
        command.downgrade(alembic_cfg, "base")

        remaining = set(inspect(create_engine(empty_database)).get_table_names())

        assert remaining <= {"alembic_version"}

    def test_the_schema_carries_the_tables_the_application_reads(
        self, empty_database: str
    ):
        command.upgrade(alembic_config(empty_database), "head")

        tables = set(inspect(create_engine(empty_database)).get_table_names())

        assert {"items", "jobs"} <= tables
